const commands=[
    "npx create-react-app google-drive-clone(Done)",
    "cd google-drive-clone;npm start(Done)",
//     "npx create-react-app custom-charts-clone(Done)",
//     "cd custom-charts-clone;npm start(Done)",
//     "cd custom-charts-clone;npm i @material-ui/core(Done)",
//     "cd custom-charts-clone;npm i @material-ui/icons(Done)",
//     "cd custom-charts-clone;npm i react-router-dom(Done)",
//     "cd custom-charts-clone;npm i styled-components(Done)",
//     "cd custom-charts-clone;npm i firebase@8.4.1(Done)",
//     "cd custom-charts-clone;npm i firebase-tools@9.9.0(Done)",
//     "cd custom-charts-clone;npm i react-redux@7.2.3(Done)",
//     "cd custom-charts-clone;npm i @reduxjs/toolkit@1.5.1(Done)",
//     "cd custom-charts-clone;npm i react-slick@0.28.1(Done)",
//     "cd custom-charts-clone;npm i slick-carousel@1.8.1(Done)",
//     "cd custom-charts-clone;npm i @amcharts/amcharts4@4.10.15(Done)",
//     "cd custom-charts-clone;npm i @types/core-js@2.5.4(Done)",
//     "cd custom-charts-clone;npm i anychart@8.9.0(Done)",
//     "cd custom-charts-clone;npm i anychart-react@1.4.1(Done)",
//     "cd custom-charts-clone;npm i apexcharts@^3.24.0(Done)",
//     "cd custom-charts-clone;npm i chart.js@2.9.4(Done)",
//     "cd custom-charts-clone;npm i core-js@3.8.3(Done)",
//     "cd custom-charts-clone;npm i d3@6.3.1(Done)",
//     "cd custom-charts-clone;npm i highcharts@9.1.0(Done)",
//     "cd custom-charts-clone;npm i highcharts-react-official@3.0.0(Done)",
//     "cd custom-charts-clone;npm i jquery@3.5.1(Done)",
//     "cd custom-charts-clone;npm i jscharting@2.9.0-6(Done)",
//     "cd custom-charts-clone;npm i jscharting-react@1.2.1(Done)",
//     "cd custom-charts-clone;npm i papaparse@5.3.0(Done)",
//     "cd custom-charts-clone;npm i plotly.js@1.58.4(Done)",
//     "cd custom-charts-clone;npm i plotly.js-basic-dist@1.58.4(Done)",
//     "cd custom-charts-clone;npm i plotly.js-dist@1.58.4(Done)",
//     "cd custom-charts-clone;npm i plotly.js-finance-dist@1.58.4(Done)",
//     "cd custom-charts-clone;npm i react-apexcharts@1.3.7(Done)",
//     "cd custom-charts-clone;npm i react-bootstrap@1.4.3(Done)",
//     "cd custom-charts-clone;npm i react-chartjs-2@2.11.1(Done)",
//     "cd custom-charts-clone;npm i react-dropdown@^1.9.2(Done)",
//     "cd custom-charts-clone;npm i react-helmet@6.1.0(Done)",
//     "cd custom-charts-clone;npm i react-plotly.js@2.5.1(Done)",
//     "cd custom-charts-clone;npm i react-router@5.2.0(Done)",
//     "cd custom-charts-clone;npm i regenerator-runtime@0.13.7(Done)",
//     "cd custom-charts-clone;npm i underscore@1.13.1(Done)",
//     "cd custom-charts-clone;npm i xlsx@0.16.9(Done)",
//     "cd custom-charts-clone;firebase init(Done)",
//     '"build": "react-scripts --max_old_space_size=4096 build"(change line in package.json)(Done)',
//     "cd custom-charts-clone;npm run build(Done)",
//     "cd custom-charts-clone;firebase deploy(Done)"
    
    // "npx create-react-app youtube-clone",
    // "cd youtube-clone;npm start",
    // "cd youtube-clone;npm i @material-ui/core",
    // "cd youtube-clone;npm i @material-ui/icons",
    // "cd youtube-clone;npm i react-router-dom",
    // "cd youtube-clone;firebase login",
    // "cd youtube-clone;firebase init",
    // "cd youtube-clone;npm run build",
    // "cd youtube-clone;firebase deploy"

    // "npx create-react-app youtube-disney-clone",
    // "cd youtube-disney-clone;npm start",
    // "cd youtube-disney-clone;npm install react-router-dom",
    // "cd youtube-disney-clone;npm i styled-components",
    // "cd youtube-disney-clone;npm i firebase@8.4.1",
    // "cd youtube-disney-clone;npm i firebase-tools@9.9.0",
    // "cd youtube-disney-clone;npm i react-redux@7.2.3",
    // "cd youtube-disney-clone;npm i @reduxjs/toolkit@1.5.1",
    // "cd youtube-disney-clone;npm i react-slick@0.28.1",
    // "cd youtube-disney-clone;npm i slick-carousel@1.8.1",
    // "cd youtube-disney-clone;firebase login",
    // "cd youtube-disney-clone;npm run build",
    // "cd youtube-disney-clone;firebase init",
    // "cd youtube-disney-clone;firebase deploy",
    
//     "npm install @material-ui/core",
// "npm install @material-ui/icons",
// "npm install react-router-dom",
// "npm i react-currency-format",
// "npm install -g firebase-tools",
// "npm install firebase",
// "firebase login",
// "firebase init",
// "npm run build",
// "firebase deploy",
// "npm install @stripe/stripe-js",
// "npm install @stripe/react-stripe-js",
// "npm install axios",
// "firebase init",
// "cd functions",
// "cd functions/npm install express",
// "cd functions/npm install cors",
// "cd functions/npm install stripe",
// "cd functions/firebase emulators:start",
// "cd amazon-clone/npm install moment"

];


 const time=["30:03"];

const url="https://www.youtube.com/watch?v=ljuCH6_jrYE";
// const python_learning_url="https://www.youtube.com/watch?v=4F2m91eKmts";
//const deployedUrl="https://custom-charts-clone.web.app";
